{
    "meals"
:
    [{
        "idMeal": "52862",
        "strMeal": "Peach & Blueberry Grunt",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Heat oven to 190C\/170C fan\/gas 5. Butter a wide shallow ovenproof dish. Blend the cornflour with the orange zest and juice, and put in a large pan with the sugar. Halve, stone and slice the peaches and add to the pan. Bring slowly to the boil, stirring gently until the sauce is shiny and thickened, about 3-4 mins. Remove from the heat, stir in the blueberries and tip into the prepared dish.\r\nTip the flour into a mixing bowl and add the 50g butter. Rub the butter into the flour until it resembles fine breadcrumbs, then stir in half the sugar. Mix the remaining sugar with the cinnamon and set aside.\r\nAdd the milk to the dry ingredients and mix to a soft dough. Turn out onto a lightly floured surface and knead briefly. Roll out to an oblong roughly 16 x 24cm. Brush with melted butter and sprinkle evenly with the spicy sugar. Roll up from one long side and cut into 12 slices. Arrange around the top of the dish, leaving the centre uncovered.\r\nBake for 20-25 mins, until the topping is crisp and golden. Serve warm.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/ssxvup1511387476.jpg",
        "strTags": "Desert,Pudding,Fruity",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=SNeO28BCpsc",
        "strIngredient1": "Corn Flour",
        "strIngredient2": "Orange",
        "strIngredient3": "Orange",
        "strIngredient4": "Caster Sugar",
        "strIngredient5": "Peaches",
        "strIngredient6": "Blueberries",
        "strIngredient7": "Self-raising Flour",
        "strIngredient8": "Butter",
        "strIngredient9": "Muscovado Sugar",
        "strIngredient10": "Cinnamon",
        "strIngredient11": "Milk",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 tsp ",
        "strMeasure2": "Juice of 2",
        "strMeasure3": "Zest of 1",
        "strMeasure4": "2 tbs",
        "strMeasure5": "6",
        "strMeasure6": "250g",
        "strMeasure7": "200g",
        "strMeasure8": "50g",
        "strMeasure9": "100g ",
        "strMeasure10": "1 tsp ",
        "strMeasure11": "6 tblsp",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/1553651\/peach-and-blueberry-grunt",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52963",
        "strMeal": "Shakshuka",
        "strDrinkAlternate": null,
        "strCategory": "Vegetarian",
        "strArea": "Egyptian",
        "strInstructions": "Heat the oil in a frying pan that has a lid, then soften the onions, chilli, garlic and coriander stalks for 5 mins until soft. Stir in the tomatoes and sugar, then bubble for 8-10 mins until thick. Can be frozen for 1 month.\r\n\r\nUsing the back of a large spoon, make 4 dips in the sauce, then crack an egg into each one. Put a lid on the pan, then cook over a low heat for 6-8 mins, until the eggs are done to your liking. Scatter with the coriander leaves and serve with crusty bread.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/g373701551450225.jpg",
        "strTags": "Egg,Brunch,Breakfast",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=C-3_jYrfdBU",
        "strIngredient1": "Olive Oil",
        "strIngredient2": "Red Onions",
        "strIngredient3": "Red Chilli",
        "strIngredient4": "Garlic",
        "strIngredient5": "Coriander",
        "strIngredient6": "Cherry Tomatoes",
        "strIngredient7": "Caster Sugar",
        "strIngredient8": "Eggs",
        "strIngredient9": "Feta",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 tbs",
        "strMeasure2": "2 chopped",
        "strMeasure3": "1 finely chopped ",
        "strMeasure4": "1 clove",
        "strMeasure5": "Chopped",
        "strMeasure6": "800g",
        "strMeasure7": "1 tbs",
        "strMeasure8": "4",
        "strMeasure9": "Spinkling",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/7573\/spicy-tomato-baked-eggs",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52842",
        "strMeal": "Broccoli & Stilton soup",
        "strDrinkAlternate": null,
        "strCategory": "Starter",
        "strArea": "British",
        "strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 \u2013 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/tvvxpv1511191952.jpg",
        "strTags": null,
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=_HgVLpmNxTY",
        "strIngredient1": "Rapeseed Oil",
        "strIngredient2": "Onion",
        "strIngredient3": "Celery",
        "strIngredient4": "Leek",
        "strIngredient5": "Potatoes",
        "strIngredient6": "Butter",
        "strIngredient7": "Vegetable Stock",
        "strIngredient8": "Broccoli",
        "strIngredient9": "Stilton Cheese",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2 tblsp ",
        "strMeasure2": "1 finely chopped ",
        "strMeasure3": "1",
        "strMeasure4": "1 sliced",
        "strMeasure5": "1 medium",
        "strMeasure6": "1 knob",
        "strMeasure7": "1 litre hot",
        "strMeasure8": "1 Head chopped",
        "strMeasure9": "140g",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/1940679\/broccoli-and-stilton-soup",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52989",
        "strMeal": "Christmas Pudding Trifle",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Peel the oranges using a sharp knife, ensuring all the pith is removed. Slice as thinly as possible and arrange over a dinner plate. Sprinkle with the demerara sugar followed by the Grand Marnier and set aside.\r\n\r\nCrumble the Christmas pudding into large pieces and scatter over the bottom of a trifle bowl. Lift the oranges onto the pudding in a layer and pour over any juices.\r\n\r\nBeat the mascarpone until smooth, then stir in the custard. Spoon the mixture over the top of the oranges.\r\n\r\nLightly whip the cream and spoon over the custard. Sprinkle with the flaked almonds and grated chocolate. You can make this a day in advance if you like, chill until ready to serve.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/r33cud1576791081.jpg",
        "strTags": "Christmas",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=jRfyNQs5qhU",
        "strIngredient1": "Orange",
        "strIngredient2": "Demerara Sugar",
        "strIngredient3": "Grand Marnier",
        "strIngredient4": "Christmas Pudding",
        "strIngredient5": "Custard",
        "strIngredient6": "Mascarpone",
        "strIngredient7": "Double Cream",
        "strIngredient8": "Flaked Almonds",
        "strIngredient9": "Dark Chocolate",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "3",
        "strMeasure2": "1 tbs",
        "strMeasure3": "2 tbs",
        "strMeasure4": "300g",
        "strMeasure5": "500g",
        "strMeasure6": "250g",
        "strMeasure7": "284ml",
        "strMeasure8": "Handful",
        "strMeasure9": "Grated",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/1826685\/christmas-pudding-trifle",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52864",
        "strMeal": "Mushroom & Chestnut Rotolo",
        "strDrinkAlternate": null,
        "strCategory": "Vegetarian",
        "strArea": "British",
        "strInstructions": "Soak the dried mushrooms in 350ml boiling water and set aside until needed. Blitz \u00be of the chestnuts with 150ml water until creamy. Roughly chop the remaining chestnuts.\r\nHeat 2 tbsp olive oil in a large non-stick frying pan. Fry the shallots with a pinch of salt until softened, then add the garlic, chopped chestnuts and rosemary, and fry for 2 mins more. Add the wild mushrooms, 2 tbsp oil and some seasoning. Cook for 3 mins until they begin to soften. Drain and roughly chop the dried mushrooms (reserve the soaking liquid), then add those too, along with the soy sauce, and fry for 2 mins more.\r\nWhisk the wine, reserved mushroom liquid and chestnut cream together to create a sauce. Season, then add half to the mushroom mixture in the pan and cook for 1 min until the sauce becomes glossy. Remove and discard the rosemary sprigs, then set the mixture aside.\r\nHeat oven to 180C\/160C fan\/gas 4. Bring a large pan of salted water to the boil and get a large bowl of ice water ready. Drop the lasagne sheets into the boiling water for 2 mins or until pliable and a little cooked, then immediately plunge them into the cold water. Using your fingers, carefully separate the sheets and transfer to a clean tea towel. Spread a good spoonful of the sauce on the bottom two thirds of each sheet, then, rolling away from yourself, roll up the shorter ends. Cut each roll in half, then position the rolls of pasta cut-side up in a pie dish that you are happy to serve from at the table. If you have any mushroom sauce remaining after you\u2019ve rolled up all the sheets, simply push it into some of the exposed rolls of pasta.\r\nPour the rest of the sauce over the top of the pasta, then bake for 10 mins or until the pasta no longer has any resistance when tested with a skewer.\r\nMeanwhile, put the breadcrumbs, the last 2 tbsp olive oil, sage leaves and some seasoning in a bowl, and toss everything together. Scatter the rotolo with the crumbs and sage, then bake for another 10 mins, until the top is golden and the sage leaves are crispy. Leave to cool for 10 mins to allow the pasta to absorb the sauce, then drizzle with a little truffle oil, if you like, before taking your dish to the table.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/ssyqwr1511451678.jpg",
        "strTags": "Vegetarian,Nutty",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=GNN7_ZSJ5YE",
        "strIngredient1": "Mushrooms",
        "strIngredient2": "Chestnuts",
        "strIngredient3": "Challots",
        "strIngredient4": "Garlic",
        "strIngredient5": "Rosemary",
        "strIngredient6": "Wild Mushrooms",
        "strIngredient7": "Soy Sauce",
        "strIngredient8": "White Wine",
        "strIngredient9": "Lasagne Sheets",
        "strIngredient10": "Breadcrumbs",
        "strIngredient11": "Sage",
        "strIngredient12": "Truffle Oil",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "30g",
        "strMeasure2": "240g",
        "strMeasure3": "3",
        "strMeasure4": "3 cloves",
        "strMeasure5": "3 sprigs",
        "strMeasure6": "500g",
        "strMeasure7": "2 tblsp ",
        "strMeasure8": "125ml ",
        "strMeasure9": "350g",
        "strMeasure10": "4 tbsp",
        "strMeasure11": "1\/2 handful ",
        "strMeasure12": "to serve",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/mushroom-chestnut-rotolo",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52841",
        "strMeal": "Creamy Tomato Soup",
        "strDrinkAlternate": null,
        "strCategory": "Starter",
        "strArea": "British",
        "strInstructions": "Put the oil, onions, celery, carrots, potatoes and bay leaves in a big casserole dish, or two saucepans. Fry gently until the onions are softened \u2013 about 10-15 mins. Fill the kettle and boil it.\r\nStir in the tomato pur\u00e9e, sugar, vinegar, chopped tomatoes and passata, then crumble in the stock cubes. Add 1 litre boiling water and bring to a simmer. Cover and simmer for 15 mins until the potato is tender, then remove the bay leaves. Pur\u00e9e with a stick blender (or ladle into a blender in batches) until very smooth. Season to taste and add a pinch more sugar if it needs it. The soup can now be cooled and chilled for up to 2 days, or frozen for up to 3 months.\r\nTo serve, reheat the soup, stirring in the milk \u2013 try not to let it boil. Serve in small bowls with cheesy sausage rolls.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/stpuws1511191310.jpg",
        "strTags": "Baking",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=lBhwjjUiFk4",
        "strIngredient1": "Olive Oil",
        "strIngredient2": "Onions",
        "strIngredient3": "Celery",
        "strIngredient4": "Carrots",
        "strIngredient5": "Potatoes",
        "strIngredient6": "Bay Leaf",
        "strIngredient7": "Tomato Puree",
        "strIngredient8": "Sugar",
        "strIngredient9": "White Vinegar",
        "strIngredient10": "Chopped Tomatoes",
        "strIngredient11": "Passata",
        "strIngredient12": "Vegetable Stock Cube",
        "strIngredient13": "Whole Milk",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "3 tbsp",
        "strMeasure2": "2 chopped",
        "strMeasure3": "2 sticks",
        "strMeasure4": "300g",
        "strMeasure5": "500g",
        "strMeasure6": "4",
        "strMeasure7": "5 tblsp ",
        "strMeasure8": "2 tblsp ",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "1\u00bd kg",
        "strMeasure11": "500g",
        "strMeasure12": "3",
        "strMeasure13": "400ml",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/2604646\/creamy-tomato-soup",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52783",
        "strMeal": "Rigatoni with fennel sausage sauce",
        "strDrinkAlternate": null,
        "strCategory": "Lamb",
        "strArea": "Moroccan",
        "strInstructions": "Heat a tablespoon of oil in a large saute pan for which you have a lid. Add the sausage pieces and fry on a medium-high heat for 10 minutes, stirring regularly, until golden-brown all over. Transfer the sausages to a plate, then add the onion and fennel to the hot pan and fry for 15 minutes, stirring once in a while, until soft and caramelised; if the pan goes a bit dry, add a teaspoon or so of extra oil. Stir in the paprika, garlic and half the fennel seeds, fry for two minutes more, then pour on the wine and boil for 30 seconds, to reduce by half. Add the tomatoes, sugar, 100ml water, the seared sausage and half a teaspoon of salt, cover and simmer for 30 minutes; remove the lid after 10 minutes, and cook until the sauce is thick and rich. Remove from the heat, stir through the olives and remaining fennel seeds and set aside until you\u2019re ready to serve.\r\n\r\nBring a large pot of salted water to a boil, add the pasta and cook for 12-14 minutes (or according to the instructions on the packet), until al dente. Meanwhile, reheat the sauce. Drain the pasta, return it to the pot, stir in a tablespoon of oil, then divide between the bowls. \r\n\r\nPut all the pesto ingredients except the basil in the small bowl of a food processor. Add a tablespoon of water and blitz to a rough paste. Add the basil, then blitz until just combined (the pesto has a much better texture if the basil is not overblended).\r\n\r\nSpoon over the rag\u00f9 and top with a spoonful of pesto. Finish with a sprinkling of chopped fennel fronds, if you have any, and serve at once.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/qtqvys1468573168.jpg",
        "strTags": "Pasta",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=45dpOfESxr8",
        "strIngredient1": "olive oil",
        "strIngredient2": "Italian fennel sausages",
        "strIngredient3": "onion",
        "strIngredient4": "fennel bulb",
        "strIngredient5": "smoky paprika",
        "strIngredient6": "garlic",
        "strIngredient7": "fennel seeds",
        "strIngredient8": "red wine",
        "strIngredient9": "chopped tomatoes",
        "strIngredient10": "caster sugar",
        "strIngredient11": "pitted black olives",
        "strIngredient12": "rigatoni",
        "strIngredient13": "pecorino",
        "strIngredient14": "anchovy fillet",
        "strIngredient15": "garlic",
        "strIngredient16": "olive oil",
        "strIngredient17": "basil leaves",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2\u00bd tbsp",
        "strMeasure2": "6 cut into 1.5cm-thick slices",
        "strMeasure3": "1 large peeled and chopped",
        "strMeasure4": "1 trimmed and roughly chopped; reserve any fronds to garnish",
        "strMeasure5": "\u00bd tsp",
        "strMeasure6": "1 clove, peeled and sliced",
        "strMeasure7": "2 tsp lightly toasted and then gently crushed",
        "strMeasure8": "100ml",
        "strMeasure9": "400g tinned",
        "strMeasure10": "\u00bd tsp",
        "strMeasure11": "50g cut in half lengthways",
        "strMeasure12": "500g",
        "strMeasure13": "30g roughly crumbled into 0.5cm pieces",
        "strMeasure14": "1  rinsed and patted dry",
        "strMeasure15": "1 clove, peeled and crushed",
        "strMeasure16": "60ml",
        "strMeasure17": "50g torn",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http:\/\/www.ottolenghi.co.uk\/recipes\/meat\/rigatoni-with-fennel-sausage-sauce-and-pecorino-and-anchovy-pesto-shop",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52792",
        "strMeal": "Bread and Butter Pudding",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Grease a 1 litre\/2 pint pie dish with butter.\r\nCut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.\r\nArrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.\r\nGently warm the milk and cream in a pan over a low heat to scalding point. Don't let it boil.\r\nCrack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.\r\nAdd the warm milk and cream mixture and stir well, then strain the custard into a bowl.\r\nPour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.\r\nPreheat the oven to 180C\/355F\/Gas 4.\r\nPlace the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/xqwwpy1483908697.jpg",
        "strTags": "Pudding,Brunch",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=Vz5W1-BmOE4",
        "strIngredient1": "butter",
        "strIngredient2": "bread",
        "strIngredient3": "sultanas",
        "strIngredient4": "cinnamon",
        "strIngredient5": "milk",
        "strIngredient6": "double cream",
        "strIngredient7": "eggs",
        "strIngredient8": "sugar",
        "strIngredient9": "nutmeg",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "25g\/1oz",
        "strMeasure2": "8 thin slices",
        "strMeasure3": "50g\/2oz",
        "strMeasure4": "2 tsp",
        "strMeasure5": "350ml\/12fl",
        "strMeasure6": "50ml\/2fl oz",
        "strMeasure7": "2 free-range",
        "strMeasure8": "25g\/1oz",
        "strMeasure9": "grated, to taste",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/cooking.nytimes.com\/recipes\/1018529-coq-au-vin",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52804",
        "strMeal": "Poutine",
        "strDrinkAlternate": null,
        "strCategory": "Miscellaneous",
        "strArea": "Canadian",
        "strInstructions": "Heat oil in a deep fryer or deep heavy skillet to 365\u00b0F (185\u00b0C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/uuyrrx1487327597.jpg",
        "strTags": "UnHealthy,Speciality,HangoverFood",
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=UVAMAoA2_WU",
        "strIngredient1": "Vegetable Oil",
        "strIngredient2": "Beef Gravy",
        "strIngredient3": "Potatoes",
        "strIngredient4": "Cheese Curds",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "Dash",
        "strMeasure2": "1 Can",
        "strMeasure3": "5 thin cut",
        "strMeasure4": "2 cups",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http:\/\/www.food.com\/recipe\/real-canadian-poutine-113388",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, {
        "idMeal": "52890",
        "strMeal": "Jam Roly-Poly",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Put a deep roasting tin onto the bottom shelf of the oven, and make sure that there\u2019s another shelf directly above it. Pull the roasting tin out on its shelf, fill two-thirds with boiling water from the kettle, then carefully slide it back in. Heat oven to 180C\/160C fan\/gas 4. Tear off a large sheet of foil and greaseproof paper (about 30 x 40cm). Sit the greaseproof on top of the foil and butter it.\r\nTip butter, flour and vanilla seeds into a food processor; pulse until the butter has disappeared. Tip into a mixing bowl. Stir through the suet, pour in the milk and work together with a cutlery knife until you get a sticky dough. You may need a drop more milk, depending on your flour.\r\nTip the dough out onto a floured surface, quickly pat together to smooth, then roll out to a square roughly 25 x 25cm. Spread the jam all over, leaving a gap along one edge, then roll up from the opposite edge. Pinch the jam-free edge into the dough where it meets, and pinch the ends roughly, too. Carefully lift onto the greased paper, join-side down (you might find a flat baking sheet helpful for this), loosely bring up the paper and foil around it, then scrunch together along the edges and ends to seal. The roly-poly will puff quite a bit during cooking so don\u2019t wrap it tightly. Lift the parcel directly onto the rack above the tin and cook for 1 hr.\r\nLet the pudding sit for 5 mins before unwrapping, then carefully open the foil and paper, and thickly slice to serve.",
        "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/ysqupp1511640538.jpg",
        "strTags": null,
        "strYoutube": "https:\/\/www.youtube.com\/watch?v=5ZYWVQ8imVA",
        "strIngredient1": "Butter",
        "strIngredient2": "Self-raising Flour",
        "strIngredient3": "Vanilla",
        "strIngredient4": "Suet",
        "strIngredient5": "Milk",
        "strIngredient6": "Raspberry Jam",
        "strIngredient7": "Custard",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "250g",
        "strMeasure3": "1 small",
        "strMeasure4": "50g",
        "strMeasure5": "150ml",
        "strMeasure6": "100g ",
        "strMeasure7": "to serve",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https:\/\/www.bbcgoodfood.com\/recipes\/13354\/jam-rolypoly",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }]
}